### ISSUE TITLE
Структура конфига

### ISSUE THREAD

**Issue by ehlvg** [danilkis/Disona#3]
Возможно, нужно исправить структуру конфига `.example/.env.template`, чтобы получилось что-то вроде:

```toml
# Secrets for token generation
ACCESS_TOKEN_SECRET="your_access_token_secret" # Secret for access token
REFRESH_TOKEN_SECRET="your_refresh_token_secret" # Secret for refresh token

# Algorithm used for token generation
ALGORITHM="HS256" # Algorithm for JWT

# Token expiration times
ACCESS_TOKEN_EXPIRE="1d" # Access token expiration (1 day)
REFRESH_TOKEN_EXPIRE="15d" # Refresh token expiration (15 days)
```

Здесь я добавил комментарии, а также изменил представление EXPIRE на "1d" вместо 1d и т. д.
